replicaCount: 2

image:
  repository: us-east1-docker.pkg.dev/venu-5198/my-repo/fastapi-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

containerPort: 8000

