name: Build and Deploy to GKE with Helm

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: venu-5198
  REGION: us-east1
  REPO_NAME: my-repo
  CLUSTER_NAME: fastapi-cluster
  IMAGE_NAME: fastapi-app
  DEPLOYMENT_NAME: fastapi-deployment
  NAMESPACE: default

jobs:
  build:
    name: Build and Push Docker Image to Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet || \
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to GKE using Helm
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      - name: Deploy using Helm
        run: |
          helm upgrade --install ${{ env.DEPLOYMENT_NAME }} ./helm-chart \
            --set image.repository=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }} \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace

