name: CI/CD - FastAPI GKE Deployment

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: venu-5198
  REGION: us-east1
  CLUSTER_NAME: fastapi-cluster
  REPOSITORY: my-repo
  IMAGE: fastapi-app
  IMAGE_URI: us-east1-docker.pkg.dev/venu-5198/my-repo/fastapi-app

jobs:
  # -------------------------------
  # CI SECTION
  # -------------------------------

  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements.txt
          pip install flake8 pytest

  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          pip install flake8
          flake8 . --max-line-length=120 --ignore=E302,E501

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements.txt
          pip install pytest
          pytest -v || true

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_URI }}:${{ github.sha }} .

      - name: Save Docker image
        run: docker save ${{ env.IMAGE_URI }}:${{ github.sha }} -o app.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-image
          path: app.tar

  trivy_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: fastapi-image
          path: .
      - run: docker load -i app.tar
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_URI }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'

  push_image:
    name: Push Image to Artifact Registry
    runs-on: ubuntu-latest
    needs: trivy_scan
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: fastapi-image
          path: .
      - run: docker load -i app.tar
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          docker push ${{ env.IMAGE_URI }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_URI }}:${{ github.sha }} ${{ env.IMAGE_URI }}:latest
          docker push ${{ env.IMAGE_URI }}:latest

  # -------------------------------
  # CD SECTION
  # -------------------------------
  deploy:
    name: Deploy to GKE with Helm
    runs-on: ubuntu-latest
    needs: push_image
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update -y
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Connect to GKE
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install fastapi-app ./helm-chart \
            --set image.repository=${{ env.IMAGE_URI }} \
            --set image.tag=${{ github.sha }}

      - name: Verify Deployment
        run: |
          kubectl get pods -l app=fastapi-app -o wide
          kubectl get svc -l app=fastapi-app -o wide
