name: CI/CD to GKE using Helm

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: venu-5198
  REGION: us-east1
  REPOSITORY: my-repo
  IMAGE: fastapi-app
  CLUSTER_NAME: fastapi-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------
      # 1️⃣ Checkout Code
      # ------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------------
      # 2️⃣ Authenticate to Google Cloud
      # ------------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ------------------------------
      # 3️⃣ Set up gcloud SDK
      # ------------------------------
      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # ------------------------------
      # 4️⃣ Install GKE Auth Plugin (FIX)
      # ------------------------------
      - name: Install GKE Auth Plugin
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      # ------------------------------
      # 5️⃣ Configure Docker authentication
      # ------------------------------
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ env.REGION }}-docker.pkg.dev

      # ------------------------------
      # 6️⃣ Build and Push Docker Image
      # ------------------------------
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1

      # ------------------------------
      # 7️⃣ Connect to GKE Cluster
      # ------------------------------
      - name: Connect to GKE cluster
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      # ------------------------------
      # 8️⃣ Deploy with Helm
      # ------------------------------
      - name: Deploy with Helm
        run: |
          helm upgrade --install fastapi-app ./helm-chart \
            --set image.repository=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }} \
            --set image.tag=${{ github.sha }}

